server:
  port: 9001

spring:
  application:
    name: gateway
  profiles:
    active: local
  cloud:
    gateway:
      routes:
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/**
        - id: service-discovery
          uri: lb://SERVICE-DISCOVERY
          predicates:
            - Path=/client/**
        - id: gateway
          uri: lb://GATEWAY
          predicates:
            - Path=/gateway/**
        - id: chatgpt-service
          uri: lb://CHATGPT-SERVICE
          predicates:
            - Path=/api/chatgpt/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management:
  endpoints:
    web:
      exposure:
        include: "*"