server:
  port: 9001

spring:
  application:
    name: gateway
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**, /login/oauth2/**, /auth/user/reissue
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthorizationHeaderFilter
        - id: service-discovery
          uri: lb://SERVICE-DISCOVERY
          predicates:
            - Path=/client/**
        - id: gateway
          uri: lb://GATEWAY
          predicates:
            - Path=/gateway/**
        - id: show-service
          uri: lb://SHOW-SERVICE
          predicates:
            - Path=/api/show/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management:
  endpoints:
    web:
      exposure:
        include: "*"