server:
  port: 0

spring:
  application:
    name: auth-service
  profiles:
    include: prod, jwt, oauth
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
